### ISSUE TITLE
Needs CDN

### ISSUE THREAD

**Issue by frasurebuilds** [muicss/mui-design-files#1]

**Comment by amorey** [comment]
Are you having trouble downloading the design files? How would a CDN help?

**Comment by frasurebuilds** [comment]
Yes I am. If I had a CDN it would be easier to use the content without having the files.

**Comment by amorey** [comment]
Can you explain what you're trying to do with the files? Sketch files are binary files so as long as you can download them you should be able to use them.

What happens when you click on these links?
https://github.com/muicss/mui-design-files/raw/master/mui-cssjs.sketch
https://github.com/muicss/mui-design-files/raw/master/mui-email.sketch

**Comment by frasurebuilds** [comment]
Never mind, I found it:

[link href="//cdn.muicss.com/mui-0.1.2/css/mui.min.css" rel="stylesheet" type="text/css" /]
[script src="//cdn.muicss.com/mui-0.1.2/js/mui.min.js"][/script]

[ ]=<>

**Comment by amorey** [comment]
I see! This is the repository for our design files. I didn't realize you were looking for the CDN url.

The CDN url is displayed in the README of the MUI source code:
https://github.com/muicss/mui

Also, the boilerplate HTML on the home page includes links to the CDN urls:
https://www.muicss.com

Let me know if you run into any other problems!
